// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: temporal/api/operatorservice/v1/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Temporal.Api.OperatorService.V1 {

  /// <summary>Holder for reflection information generated from temporal/api/operatorservice/v1/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for temporal/api/operatorservice/v1/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci10ZW1wb3JhbC9hcGkvb3BlcmF0b3JzZXJ2aWNlL3YxL3NlcnZpY2UucHJv",
            "dG8SH3RlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEaNnRlbXBvcmFs",
            "L2FwaS9vcGVyYXRvcnNlcnZpY2UvdjEvcmVxdWVzdF9yZXNwb25zZS5wcm90",
            "bzLcAwoPT3BlcmF0b3JTZXJ2aWNlEpIBChNBZGRTZWFyY2hBdHRyaWJ1dGVz",
            "EjsudGVtcG9yYWwuYXBpLm9wZXJhdG9yc2VydmljZS52MS5BZGRTZWFyY2hB",
            "dHRyaWJ1dGVzUmVxdWVzdBo8LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZp",
            "Y2UudjEuQWRkU2VhcmNoQXR0cmlidXRlc1Jlc3BvbnNlIgASmwEKFlJlbW92",
            "ZVNlYXJjaEF0dHJpYnV0ZXMSPi50ZW1wb3JhbC5hcGkub3BlcmF0b3JzZXJ2",
            "aWNlLnYxLlJlbW92ZVNlYXJjaEF0dHJpYnV0ZXNSZXF1ZXN0Gj8udGVtcG9y",
            "YWwuYXBpLm9wZXJhdG9yc2VydmljZS52MS5SZW1vdmVTZWFyY2hBdHRyaWJ1",
            "dGVzUmVzcG9uc2UiABKVAQoUTGlzdFNlYXJjaEF0dHJpYnV0ZXMSPC50ZW1w",
            "b3JhbC5hcGkub3BlcmF0b3JzZXJ2aWNlLnYxLkxpc3RTZWFyY2hBdHRyaWJ1",
            "dGVzUmVxdWVzdBo9LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEu",
            "TGlzdFNlYXJjaEF0dHJpYnV0ZXNSZXNwb25zZSIAQrIBCiJpby50ZW1wb3Jh",
            "bC5hcGkub3BlcmF0b3JzZXJ2aWNlLnYxQgxTZXJ2aWNlUHJvdG9QAVo1Z28u",
            "dGVtcG9yYWwuaW8vYXBpL29wZXJhdG9yc2VydmljZS92MTtvcGVyYXRvcnNl",
            "cnZpY2WqAh9UZW1wb3JhbC5BcGkuT3BlcmF0b3JTZXJ2aWNlLlYx6gIiVGVt",
            "cG9yYWw6OkFwaTo6T3BlcmF0b3JTZXJ2aWNlOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Temporal.Api.OperatorService.V1.RequestResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
